// TODO: Remove this file when teacher API endpoints are implemented
import type { Teacher } from "@/api/models/teacher";

export const DUMMY_TEACHERS: Teacher[] = [
  {
    id: 1,
    firstName: "Maria",
    lastName: "Santos",
    middleName: "Cruz",
    email: "maria.santos@university.edu",
    phoneNumber: "+63 912 345 6789",
    college: { id: 1, name: "College of Engineering" },
    academicTitle: "Associate Professor",
    department: { id: 1, name: "Computer Engineering" },
    qualification: "Ph.D. in Computer Science, M.Sc. in Software Engineering",
    specialization: "Machine Learning, Data Mining",
    officeLocation: "Engineering Building, Room 302",
    officeHours: "MWF 10:00 AM - 12:00 PM",
    biography:
      "Dr. Santos is an experienced educator with over 15 years of teaching and research in machine learning and data systems.",
    subjects: [
      { id: 1, code: "CS101", title: "Introduction to Programming" },
      { id: 5, code: "CS301", title: "Machine Learning" },
    ],
    createdAt: "2024-01-10",
  },
  {
    id: 2,
    firstName: "Jose",
    lastName: "Reyes",
    middleName: "Dela",
    email: "jose.reyes@university.edu",
    phoneNumber: "+63 917 654 3210",
    college: { id: 2, name: "College of Science" },
    academicTitle: "Professor",
    department: { id: 2, name: "Mathematics" },
    qualification: "Ph.D. in Mathematics, M.Sc. in Applied Mathematics",
    specialization: "Differential Equations, Linear Algebra",
    officeLocation: "Science Building, Room 115",
    officeHours: "TTh 1:00 PM - 3:00 PM",
    biography:
      "Prof. Reyes has published over 30 research papers in applied mathematics and has been teaching for 20 years.",
    subjects: [
      { id: 2, code: "MATH101", title: "College Algebra" },
      { id: 6, code: "MATH201", title: "Calculus I" },
    ],
    createdAt: "2024-01-15",
  },
  {
    id: 3,
    firstName: "Ana",
    lastName: "Garcia",
    middleName: "Lopez",
    email: "ana.garcia@university.edu",
    phoneNumber: "+63 918 765 4321",
    college: { id: 3, name: "College of Arts and Sciences" },
    academicTitle: "Assistant Professor",
    department: { id: 3, name: "Physics" },
    qualification: "M.Sc. in Physics",
    specialization: "Quantum Mechanics, Thermodynamics",
    officeLocation: "Arts Building, Room 210",
    officeHours: "MWF 2:00 PM - 4:00 PM",
    subjects: [
      { id: 3, code: "PHY101", title: "General Physics I" },
      { id: 7, code: "PHY102", title: "General Physics II" },
    ],
    createdAt: "2024-02-01",
  },
  {
    id: 4,
    firstName: "Carlos",
    lastName: "Mendoza",
    middleName: "Rivera",
    email: "carlos.mendoza@university.edu",
    phoneNumber: "+63 919 876 5432",
    college: { id: 1, name: "College of Engineering" },
    academicTitle: "Instructor",
    department: { id: 4, name: "Electronics Engineering" },
    qualification: "M.Sc. in Electronics and Communications Engineering",
    specialization: "Digital Systems, Embedded Systems",
    officeLocation: "Engineering Building, Room 201",
    officeHours: "TTh 9:00 AM - 11:00 AM",
    subjects: [
      { id: 4, code: "EE101", title: "Basic Electrical Engineering" },
      { id: 8, code: "EE201", title: "Digital Electronics" },
    ],
    createdAt: "2024-02-10",
  },
  {
    id: 5,
    firstName: "Liza",
    lastName: "Villanueva",
    middleName: "Torres",
    email: "liza.villanueva@university.edu",
    phoneNumber: "+63 920 987 6543",
    college: { id: 2, name: "College of Science" },
    academicTitle: "Associate Professor",
    department: { id: 5, name: "Chemistry" },
    qualification:
      "Ph.D. in Chemistry, M.Sc. in Organic Chemistry, B.Sc. in Chemistry",
    specialization: "Organic Chemistry, Biochemistry",
    officeLocation: "Science Building, Room 320",
    officeHours: "MWF 8:00 AM - 10:00 AM",
    biography:
      "Dr. Villanueva specializes in organic synthesis and has collaborated with international research institutions.",
    subjects: [
      { id: 9, code: "CHEM101", title: "General Chemistry" },
      { id: 10, code: "CHEM201", title: "Organic Chemistry" },
    ],
    createdAt: "2024-03-05",
  },
];
