ALTER DATABASE CURRENT SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO

ALTER DATABASE CURRENT SET READ_COMMITTED_SNAPSHOT ON
GO

ALTER DATABASE CURRENT SET ALLOW_SNAPSHOT_ISOLATION ON
GO

ALTER DATABASE CURRENT SET MULTI_USER
GO
