using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Enrollify.Infrastructure.Generator;

/// <summary>
/// Generates Dapper type handlers for Vogen value objects at compile time using source generators.
/// </summary>
/// <remarks>This generator scans the compilation for types annotated with the Vogen ValueObject attribute and
/// produces Dapper type handler classes for each detected value object. It also generates a registration class to
/// simplify the process of registering all generated type handlers with Dapper. Use this generator to enable seamless
/// mapping of Vogen value objects in Dapper queries and commands.</remarks>
[Generator]
public class DapperTypeHandlerGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Get the compilation
        var compilation = context.CompilationProvider;

        // Generate type handlers from compilation (includes referenced assemblies)
        context.RegisterSourceOutput(compilation, static (spc, compilation) =>
        {
            var vogenTypes = GetAllVogenTypes(compilation);

            foreach (var type in vogenTypes)
            {
                var handlerName = $"{type.SimpleName}DapperTypeHandler";
                string source = GenerateTypeHandler(handlerName, type.FullName, type.UnderlyingType, type.Namespace);
                spc.AddSource($"{handlerName}.g.cs", source);
            }

            // Generate registration class
            if (vogenTypes.Count > 0)
            {
                string registrationSource = GenerateRegistrationClass(vogenTypes);
                spc.AddSource("VogenDapperTypeHandlerRegistration.g.cs", registrationSource);
            }
        });
    }

    private static List<VogenTypeInfo> GetAllVogenTypes(Compilation compilation)
    {
        var vogenTypes = new List<VogenTypeInfo>();

        // Scan all types in the compilation (including referenced assemblies)
        var allTypes = GetAllTypes(compilation.GlobalNamespace);

        foreach (var type in allTypes)
        {
            if (type.TypeKind != TypeKind.Struct && type.TypeKind != TypeKind.Class)
                continue;

            // Look for ValueObject attribute from Vogen
            foreach (var attr in type.GetAttributes())
            {
                var attrClass = attr.AttributeClass;
                if (attrClass == null)
                    continue;

                // Check if it's the Vogen ValueObject attribute
                if (attrClass.Name != "ValueObjectAttribute" && !attrClass.Name.StartsWith("ValueObject"))
                    continue;

                if (attrClass.ContainingNamespace?.ToDisplayString() != "Vogen")
                    continue;

                // Extract the underlying type from the attribute's generic argument
                string underlyingType = "object";
                if (attrClass.TypeArguments.Length > 0)
                {
                    underlyingType = attrClass.TypeArguments[0].ToDisplayString();
                }

                vogenTypes.Add(new VogenTypeInfo
                {
                    FullName = type.ToDisplayString(),
                    SimpleName = type.Name,
                    UnderlyingType = underlyingType,
                    Namespace = type.ContainingNamespace.ToDisplayString()
                });
                break;
            }
        }

        return vogenTypes;
    }

    private static IEnumerable<INamedTypeSymbol> GetAllTypes(INamespaceSymbol namespaceSymbol)
    {
        foreach (var type in namespaceSymbol.GetTypeMembers())
        {
            yield return type;

            // Recursively get nested types
            foreach (var nestedType in GetNestedTypes(type))
            {
                yield return nestedType;
            }
        }

        foreach (var childNamespace in namespaceSymbol.GetNamespaceMembers())
        {
            foreach (var type in GetAllTypes(childNamespace))
            {
                yield return type;
            }
        }
    }

    private static IEnumerable<INamedTypeSymbol> GetNestedTypes(INamedTypeSymbol type)
    {
        foreach (var nestedType in type.GetTypeMembers())
        {
            yield return nestedType;

            foreach (var nested in GetNestedTypes(nestedType))
            {
                yield return nested;
            }
        }
    }

    private static string GenerateTypeHandler(string handlerName, string voType, string underlyingType, string valueObjectNamespace)
    {
        return $@"// <auto-generated/>
using System.Data;
using Dapper;
using {valueObjectNamespace};

namespace Enrollify.Infrastructure.Data.Dapper.Generated
{{
    /// <summary>
    /// Dapper type handler for {voType}
    /// </summary>
    public sealed class {handlerName} : SqlMapper.TypeHandler<{voType}>
    {{
        public override void SetValue(IDbDataParameter parameter, {voType} value)
        {{
            parameter.Value = value.Value;
        }}

        public override {voType} Parse(object value)
        {{
            return {voType}.From(({underlyingType})value);
        }}
    }}
}}";
    }

    private static string GenerateRegistrationClass(IEnumerable<VogenTypeInfo> vogenTypes)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Dapper;");
        sb.AppendLine();
        
        // Add distinct namespaces
        var namespaces = vogenTypes.Select(t => t.Namespace).Distinct().OrderBy(ns => ns);
        foreach (var ns in namespaces)
        {
            sb.AppendLine($"using {ns};");
        }
        
        sb.AppendLine();
        sb.AppendLine("namespace Enrollify.Infrastructure.Data.Dapper.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Auto-generated registration for Vogen Dapper type handlers");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class VogenDapperTypeHandlerRegistration");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Registers all Vogen type handlers with Dapper");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static void RegisterTypeHandlers()");
        sb.AppendLine("        {");
        
        foreach (var type in vogenTypes.OrderBy(t => t.FullName))
        {
            sb.AppendLine($"            SqlMapper.AddTypeHandler(new {type.SimpleName}DapperTypeHandler());");
        }
        
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        
        return sb.ToString();
    }

    class VogenTypeInfo
    {
        public string FullName { get; set; } = string.Empty;
        public string SimpleName { get; set; } = string.Empty;
        public string UnderlyingType { get; set; } = string.Empty;
        public string Namespace { get; set; } = string.Empty;
    }

}