<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.SmartEnum"/>
    <PackageReference Include="libphonenumber-csharp" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Riok.Mapperly" />
    <PackageReference Include="Vogen"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Enrollify.SharedKernel\Enrollify.SharedKernel.csproj"/>
    <ProjectReference Include="..\Enrollify.Analyzers\Enrollify.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Aggregates\NotificationAggregate\Events\" />
  </ItemGroup>

</Project>
