/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteRouteImport } from './routes/portal/route'
import { Route as PortalCurriculumAndSchedulingRouteRouteImport } from './routes/portal/curriculum-and-scheduling/route'
import { Route as PortalHomeRouteImport } from './routes/portal/home'
import { Route as PortalMasterDataRouteRouteImport } from './routes/portal/master-data/route'
import { Route as PortalNotificationsRouteImport } from './routes/portal/notifications'
import { Route as PortalCurriculumAndSchedulingAcademicYearRouteImport } from './routes/portal/curriculum-and-scheduling/academic-year'
import { Route as PortalCurriculumAndSchedulingSectionsRouteImport } from './routes/portal/curriculum-and-scheduling/sections'
import { Route as PortalCurriculumAndSchedulingTeachersRouteImport } from './routes/portal/curriculum-and-scheduling/teachers'
import { Route as PortalMasterDataBuildingsRouteImport } from './routes/portal/master-data/buildings'
import { Route as PortalMasterDataCollegesRouteImport } from './routes/portal/master-data/colleges'
import { Route as PortalMasterDataCoursesRouteImport } from './routes/portal/master-data/courses'
import { Route as PortalMasterDataDepartmentsRouteImport } from './routes/portal/master-data/departments'
import { Route as PortalMasterDataRoomsRouteImport } from './routes/portal/master-data/rooms'
import { Route as PortalMasterDataSubjectsRouteImport } from './routes/portal/master-data/subjects'
import { Route as PortalCurriculumAndSchedulingCurriculumChar123CurriculumIdChar125RouteImport } from './routes/portal/curriculum-and-scheduling/curriculum.{-$curriculumId}'
import { Route as PortalCurriculumAndSchedulingSchedulingSectionsRouteImport } from './routes/portal/curriculum-and-scheduling/scheduling/sections'
import { Route as PortalCurriculumAndSchedulingSectionsDetailsSectionIdRouteImport } from './routes/portal/curriculum-and-scheduling/sections-details.$sectionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalCurriculumAndSchedulingRouteRoute =
  PortalCurriculumAndSchedulingRouteRouteImport.update({
    id: '/curriculum-and-scheduling',
    path: '/curriculum-and-scheduling',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalHomeRoute = PortalHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalMasterDataRouteRoute = PortalMasterDataRouteRouteImport.update({
  id: '/master-data',
  path: '/master-data',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalNotificationsRoute = PortalNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalCurriculumAndSchedulingAcademicYearRoute =
  PortalCurriculumAndSchedulingAcademicYearRouteImport.update({
    id: '/academic-year',
    path: '/academic-year',
    getParentRoute: () => PortalCurriculumAndSchedulingRouteRoute,
  } as any)
const PortalCurriculumAndSchedulingSectionsRoute =
  PortalCurriculumAndSchedulingSectionsRouteImport.update({
    id: '/sections',
    path: '/sections',
    getParentRoute: () => PortalCurriculumAndSchedulingRouteRoute,
  } as any)
const PortalCurriculumAndSchedulingTeachersRoute =
  PortalCurriculumAndSchedulingTeachersRouteImport.update({
    id: '/teachers',
    path: '/teachers',
    getParentRoute: () => PortalCurriculumAndSchedulingRouteRoute,
  } as any)
const PortalMasterDataBuildingsRoute =
  PortalMasterDataBuildingsRouteImport.update({
    id: '/buildings',
    path: '/buildings',
    getParentRoute: () => PortalMasterDataRouteRoute,
  } as any)
const PortalMasterDataCollegesRoute =
  PortalMasterDataCollegesRouteImport.update({
    id: '/colleges',
    path: '/colleges',
    getParentRoute: () => PortalMasterDataRouteRoute,
  } as any)
const PortalMasterDataCoursesRoute = PortalMasterDataCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => PortalMasterDataRouteRoute,
} as any)
const PortalMasterDataDepartmentsRoute =
  PortalMasterDataDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => PortalMasterDataRouteRoute,
  } as any)
const PortalMasterDataRoomsRoute = PortalMasterDataRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => PortalMasterDataRouteRoute,
} as any)
const PortalMasterDataSubjectsRoute =
  PortalMasterDataSubjectsRouteImport.update({
    id: '/subjects',
    path: '/subjects',
    getParentRoute: () => PortalMasterDataRouteRoute,
  } as any)
const PortalCurriculumAndSchedulingCurriculumChar123CurriculumIdChar125Route =
  PortalCurriculumAndSchedulingCurriculumChar123CurriculumIdChar125RouteImport.update(
    {
      id: '/curriculum/{-$curriculumId}',
      path: '/curriculum/{-$curriculumId}',
      getParentRoute: () => PortalCurriculumAndSchedulingRouteRoute,
    } as any,
  )
const PortalCurriculumAndSchedulingSchedulingSectionsRoute =
  PortalCurriculumAndSchedulingSchedulingSectionsRouteImport.update({
    id: '/scheduling/sections',
    path: '/scheduling/sections',
    getParentRoute: () => PortalCurriculumAndSchedulingRouteRoute,
  } as any)
const PortalCurriculumAndSchedulingSectionsDetailsSectionIdRoute =
  PortalCurriculumAndSchedulingSectionsDetailsSectionIdRouteImport.update({
    id: '/sections-details/$sectionId',
    path: '/sections-details/$sectionId',
    getParentRoute: () => PortalCurriculumAndSchedulingRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/portal/curriculum-and-scheduling': typeof PortalCurriculumAndSchedulingRouteRouteWithChildren
  '/portal/master-data': typeof PortalMasterDataRouteRouteWithChildren
  '/portal/home': typeof PortalHomeRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/curriculum-and-scheduling/academic-year': typeof PortalCurriculumAndSchedulingAcademicYearRoute
  '/portal/curriculum-and-scheduling/sections': typeof PortalCurriculumAndSchedulingSectionsRoute
  '/portal/curriculum-and-scheduling/teachers': typeof PortalCurriculumAndSchedulingTeachersRoute
  '/portal/master-data/buildings': typeof PortalMasterDataBuildingsRoute
  '/portal/master-data/colleges': typeof PortalMasterDataCollegesRoute
  '/portal/master-data/courses': typeof PortalMasterDataCoursesRoute
  '/portal/master-data/departments': typeof PortalMasterDataDepartmentsRoute
  '/portal/master-data/rooms': typeof PortalMasterDataRoomsRoute
  '/portal/master-data/subjects': typeof PortalMasterDataSubjectsRoute
  '/portal/curriculum-and-scheduling/curriculum/{-$curriculumId}': typeof PortalCurriculumAndSchedulingCurriculumChar123CurriculumIdChar125Route
  '/portal/curriculum-and-scheduling/scheduling/sections': typeof PortalCurriculumAndSchedulingSchedulingSectionsRoute
  '/portal/curriculum-and-scheduling/sections-details/$sectionId': typeof PortalCurriculumAndSchedulingSectionsDetailsSectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/portal/curriculum-and-scheduling': typeof PortalCurriculumAndSchedulingRouteRouteWithChildren
  '/portal/master-data': typeof PortalMasterDataRouteRouteWithChildren
  '/portal/home': typeof PortalHomeRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/curriculum-and-scheduling/academic-year': typeof PortalCurriculumAndSchedulingAcademicYearRoute
  '/portal/curriculum-and-scheduling/sections': typeof PortalCurriculumAndSchedulingSectionsRoute
  '/portal/curriculum-and-scheduling/teachers': typeof PortalCurriculumAndSchedulingTeachersRoute
  '/portal/master-data/buildings': typeof PortalMasterDataBuildingsRoute
  '/portal/master-data/colleges': typeof PortalMasterDataCollegesRoute
  '/portal/master-data/courses': typeof PortalMasterDataCoursesRoute
  '/portal/master-data/departments': typeof PortalMasterDataDepartmentsRoute
  '/portal/master-data/rooms': typeof PortalMasterDataRoomsRoute
  '/portal/master-data/subjects': typeof PortalMasterDataSubjectsRoute
  '/portal/curriculum-and-scheduling/curriculum/{-$curriculumId}': typeof PortalCurriculumAndSchedulingCurriculumChar123CurriculumIdChar125Route
  '/portal/curriculum-and-scheduling/scheduling/sections': typeof PortalCurriculumAndSchedulingSchedulingSectionsRoute
  '/portal/curriculum-and-scheduling/sections-details/$sectionId': typeof PortalCurriculumAndSchedulingSectionsDetailsSectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/portal/curriculum-and-scheduling': typeof PortalCurriculumAndSchedulingRouteRouteWithChildren
  '/portal/master-data': typeof PortalMasterDataRouteRouteWithChildren
  '/portal/home': typeof PortalHomeRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/curriculum-and-scheduling/academic-year': typeof PortalCurriculumAndSchedulingAcademicYearRoute
  '/portal/curriculum-and-scheduling/sections': typeof PortalCurriculumAndSchedulingSectionsRoute
  '/portal/curriculum-and-scheduling/teachers': typeof PortalCurriculumAndSchedulingTeachersRoute
  '/portal/master-data/buildings': typeof PortalMasterDataBuildingsRoute
  '/portal/master-data/colleges': typeof PortalMasterDataCollegesRoute
  '/portal/master-data/courses': typeof PortalMasterDataCoursesRoute
  '/portal/master-data/departments': typeof PortalMasterDataDepartmentsRoute
  '/portal/master-data/rooms': typeof PortalMasterDataRoomsRoute
  '/portal/master-data/subjects': typeof PortalMasterDataSubjectsRoute
  '/portal/curriculum-and-scheduling/curriculum/{-$curriculumId}': typeof PortalCurriculumAndSchedulingCurriculumChar123CurriculumIdChar125Route
  '/portal/curriculum-and-scheduling/scheduling/sections': typeof PortalCurriculumAndSchedulingSchedulingSectionsRoute
  '/portal/curriculum-and-scheduling/sections-details/$sectionId': typeof PortalCurriculumAndSchedulingSectionsDetailsSectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/portal'
    | '/login'
    | '/portal/curriculum-and-scheduling'
    | '/portal/master-data'
    | '/portal/home'
    | '/portal/notifications'
    | '/portal/curriculum-and-scheduling/academic-year'
    | '/portal/curriculum-and-scheduling/sections'
    | '/portal/curriculum-and-scheduling/teachers'
    | '/portal/master-data/buildings'
    | '/portal/master-data/colleges'
    | '/portal/master-data/courses'
    | '/portal/master-data/departments'
    | '/portal/master-data/rooms'
    | '/portal/master-data/subjects'
    | '/portal/curriculum-and-scheduling/curriculum/{-$curriculumId}'
    | '/portal/curriculum-and-scheduling/scheduling/sections'
    | '/portal/curriculum-and-scheduling/sections-details/$sectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/portal'
    | '/login'
    | '/portal/curriculum-and-scheduling'
    | '/portal/master-data'
    | '/portal/home'
    | '/portal/notifications'
    | '/portal/curriculum-and-scheduling/academic-year'
    | '/portal/curriculum-and-scheduling/sections'
    | '/portal/curriculum-and-scheduling/teachers'
    | '/portal/master-data/buildings'
    | '/portal/master-data/colleges'
    | '/portal/master-data/courses'
    | '/portal/master-data/departments'
    | '/portal/master-data/rooms'
    | '/portal/master-data/subjects'
    | '/portal/curriculum-and-scheduling/curriculum/{-$curriculumId}'
    | '/portal/curriculum-and-scheduling/scheduling/sections'
    | '/portal/curriculum-and-scheduling/sections-details/$sectionId'
  id:
    | '__root__'
    | '/'
    | '/portal'
    | '/login'
    | '/portal/curriculum-and-scheduling'
    | '/portal/master-data'
    | '/portal/home'
    | '/portal/notifications'
    | '/portal/curriculum-and-scheduling/academic-year'
    | '/portal/curriculum-and-scheduling/sections'
    | '/portal/curriculum-and-scheduling/teachers'
    | '/portal/master-data/buildings'
    | '/portal/master-data/colleges'
    | '/portal/master-data/courses'
    | '/portal/master-data/departments'
    | '/portal/master-data/rooms'
    | '/portal/master-data/subjects'
    | '/portal/curriculum-and-scheduling/curriculum/{-$curriculumId}'
    | '/portal/curriculum-and-scheduling/scheduling/sections'
    | '/portal/curriculum-and-scheduling/sections-details/$sectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/curriculum-and-scheduling': {
      id: '/portal/curriculum-and-scheduling'
      path: '/curriculum-and-scheduling'
      fullPath: '/portal/curriculum-and-scheduling'
      preLoaderRoute: typeof PortalCurriculumAndSchedulingRouteRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/home': {
      id: '/portal/home'
      path: '/home'
      fullPath: '/portal/home'
      preLoaderRoute: typeof PortalHomeRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/master-data': {
      id: '/portal/master-data'
      path: '/master-data'
      fullPath: '/portal/master-data'
      preLoaderRoute: typeof PortalMasterDataRouteRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/notifications': {
      id: '/portal/notifications'
      path: '/notifications'
      fullPath: '/portal/notifications'
      preLoaderRoute: typeof PortalNotificationsRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/curriculum-and-scheduling/academic-year': {
      id: '/portal/curriculum-and-scheduling/academic-year'
      path: '/academic-year'
      fullPath: '/portal/curriculum-and-scheduling/academic-year'
      preLoaderRoute: typeof PortalCurriculumAndSchedulingAcademicYearRouteImport
      parentRoute: typeof PortalCurriculumAndSchedulingRouteRoute
    }
    '/portal/curriculum-and-scheduling/sections': {
      id: '/portal/curriculum-and-scheduling/sections'
      path: '/sections'
      fullPath: '/portal/curriculum-and-scheduling/sections'
      preLoaderRoute: typeof PortalCurriculumAndSchedulingSectionsRouteImport
      parentRoute: typeof PortalCurriculumAndSchedulingRouteRoute
    }
    '/portal/curriculum-and-scheduling/teachers': {
      id: '/portal/curriculum-and-scheduling/teachers'
      path: '/teachers'
      fullPath: '/portal/curriculum-and-scheduling/teachers'
      preLoaderRoute: typeof PortalCurriculumAndSchedulingTeachersRouteImport
      parentRoute: typeof PortalCurriculumAndSchedulingRouteRoute
    }
    '/portal/master-data/buildings': {
      id: '/portal/master-data/buildings'
      path: '/buildings'
      fullPath: '/portal/master-data/buildings'
      preLoaderRoute: typeof PortalMasterDataBuildingsRouteImport
      parentRoute: typeof PortalMasterDataRouteRoute
    }
    '/portal/master-data/colleges': {
      id: '/portal/master-data/colleges'
      path: '/colleges'
      fullPath: '/portal/master-data/colleges'
      preLoaderRoute: typeof PortalMasterDataCollegesRouteImport
      parentRoute: typeof PortalMasterDataRouteRoute
    }
    '/portal/master-data/courses': {
      id: '/portal/master-data/courses'
      path: '/courses'
      fullPath: '/portal/master-data/courses'
      preLoaderRoute: typeof PortalMasterDataCoursesRouteImport
      parentRoute: typeof PortalMasterDataRouteRoute
    }
    '/portal/master-data/departments': {
      id: '/portal/master-data/departments'
      path: '/departments'
      fullPath: '/portal/master-data/departments'
      preLoaderRoute: typeof PortalMasterDataDepartmentsRouteImport
      parentRoute: typeof PortalMasterDataRouteRoute
    }
    '/portal/master-data/rooms': {
      id: '/portal/master-data/rooms'
      path: '/rooms'
      fullPath: '/portal/master-data/rooms'
      preLoaderRoute: typeof PortalMasterDataRoomsRouteImport
      parentRoute: typeof PortalMasterDataRouteRoute
    }
    '/portal/master-data/subjects': {
      id: '/portal/master-data/subjects'
      path: '/subjects'
      fullPath: '/portal/master-data/subjects'
      preLoaderRoute: typeof PortalMasterDataSubjectsRouteImport
      parentRoute: typeof PortalMasterDataRouteRoute
    }
    '/portal/curriculum-and-scheduling/curriculum/{-$curriculumId}': {
      id: '/portal/curriculum-and-scheduling/curriculum/{-$curriculumId}'
      path: '/curriculum/{-$curriculumId}'
      fullPath: '/portal/curriculum-and-scheduling/curriculum/{-$curriculumId}'
      preLoaderRoute: typeof PortalCurriculumAndSchedulingCurriculumChar123CurriculumIdChar125RouteImport
      parentRoute: typeof PortalCurriculumAndSchedulingRouteRoute
    }
    '/portal/curriculum-and-scheduling/scheduling/sections': {
      id: '/portal/curriculum-and-scheduling/scheduling/sections'
      path: '/scheduling/sections'
      fullPath: '/portal/curriculum-and-scheduling/scheduling/sections'
      preLoaderRoute: typeof PortalCurriculumAndSchedulingSchedulingSectionsRouteImport
      parentRoute: typeof PortalCurriculumAndSchedulingRouteRoute
    }
    '/portal/curriculum-and-scheduling/sections-details/$sectionId': {
      id: '/portal/curriculum-and-scheduling/sections-details/$sectionId'
      path: '/sections-details/$sectionId'
      fullPath: '/portal/curriculum-and-scheduling/sections-details/$sectionId'
      preLoaderRoute: typeof PortalCurriculumAndSchedulingSectionsDetailsSectionIdRouteImport
      parentRoute: typeof PortalCurriculumAndSchedulingRouteRoute
    }
  }
}

interface PortalCurriculumAndSchedulingRouteRouteChildren {
  PortalCurriculumAndSchedulingAcademicYearRoute: typeof PortalCurriculumAndSchedulingAcademicYearRoute
  PortalCurriculumAndSchedulingSectionsRoute: typeof PortalCurriculumAndSchedulingSectionsRoute
  PortalCurriculumAndSchedulingTeachersRoute: typeof PortalCurriculumAndSchedulingTeachersRoute
  PortalCurriculumAndSchedulingCurriculumChar123CurriculumIdChar125Route: typeof PortalCurriculumAndSchedulingCurriculumChar123CurriculumIdChar125Route
  PortalCurriculumAndSchedulingSchedulingSectionsRoute: typeof PortalCurriculumAndSchedulingSchedulingSectionsRoute
  PortalCurriculumAndSchedulingSectionsDetailsSectionIdRoute: typeof PortalCurriculumAndSchedulingSectionsDetailsSectionIdRoute
}

const PortalCurriculumAndSchedulingRouteRouteChildren: PortalCurriculumAndSchedulingRouteRouteChildren =
  {
    PortalCurriculumAndSchedulingAcademicYearRoute:
      PortalCurriculumAndSchedulingAcademicYearRoute,
    PortalCurriculumAndSchedulingSectionsRoute:
      PortalCurriculumAndSchedulingSectionsRoute,
    PortalCurriculumAndSchedulingTeachersRoute:
      PortalCurriculumAndSchedulingTeachersRoute,
    PortalCurriculumAndSchedulingCurriculumChar123CurriculumIdChar125Route:
      PortalCurriculumAndSchedulingCurriculumChar123CurriculumIdChar125Route,
    PortalCurriculumAndSchedulingSchedulingSectionsRoute:
      PortalCurriculumAndSchedulingSchedulingSectionsRoute,
    PortalCurriculumAndSchedulingSectionsDetailsSectionIdRoute:
      PortalCurriculumAndSchedulingSectionsDetailsSectionIdRoute,
  }

const PortalCurriculumAndSchedulingRouteRouteWithChildren =
  PortalCurriculumAndSchedulingRouteRoute._addFileChildren(
    PortalCurriculumAndSchedulingRouteRouteChildren,
  )

interface PortalMasterDataRouteRouteChildren {
  PortalMasterDataBuildingsRoute: typeof PortalMasterDataBuildingsRoute
  PortalMasterDataCollegesRoute: typeof PortalMasterDataCollegesRoute
  PortalMasterDataCoursesRoute: typeof PortalMasterDataCoursesRoute
  PortalMasterDataDepartmentsRoute: typeof PortalMasterDataDepartmentsRoute
  PortalMasterDataRoomsRoute: typeof PortalMasterDataRoomsRoute
  PortalMasterDataSubjectsRoute: typeof PortalMasterDataSubjectsRoute
}

const PortalMasterDataRouteRouteChildren: PortalMasterDataRouteRouteChildren = {
  PortalMasterDataBuildingsRoute: PortalMasterDataBuildingsRoute,
  PortalMasterDataCollegesRoute: PortalMasterDataCollegesRoute,
  PortalMasterDataCoursesRoute: PortalMasterDataCoursesRoute,
  PortalMasterDataDepartmentsRoute: PortalMasterDataDepartmentsRoute,
  PortalMasterDataRoomsRoute: PortalMasterDataRoomsRoute,
  PortalMasterDataSubjectsRoute: PortalMasterDataSubjectsRoute,
}

const PortalMasterDataRouteRouteWithChildren =
  PortalMasterDataRouteRoute._addFileChildren(
    PortalMasterDataRouteRouteChildren,
  )

interface PortalRouteRouteChildren {
  PortalCurriculumAndSchedulingRouteRoute: typeof PortalCurriculumAndSchedulingRouteRouteWithChildren
  PortalMasterDataRouteRoute: typeof PortalMasterDataRouteRouteWithChildren
  PortalHomeRoute: typeof PortalHomeRoute
  PortalNotificationsRoute: typeof PortalNotificationsRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalCurriculumAndSchedulingRouteRoute:
    PortalCurriculumAndSchedulingRouteRouteWithChildren,
  PortalMasterDataRouteRoute: PortalMasterDataRouteRouteWithChildren,
  PortalHomeRoute: PortalHomeRoute,
  PortalNotificationsRoute: PortalNotificationsRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
