/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteRouteImport } from './routes/portal/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalHomeRouteImport } from './routes/portal/home'
import { Route as PortalMasterDataRouteRouteImport } from './routes/portal/master-data/route'
import { Route as PortalMasterDataRoomsRouteImport } from './routes/portal/master-data/rooms'
import { Route as PortalMasterDataDepartmentsRouteImport } from './routes/portal/master-data/departments'
import { Route as PortalMasterDataCollegesRouteImport } from './routes/portal/master-data/colleges'
import { Route as PortalMasterDataBuildingsRouteImport } from './routes/portal/master-data/buildings'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalHomeRoute = PortalHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalMasterDataRouteRoute = PortalMasterDataRouteRouteImport.update({
  id: '/master-data',
  path: '/master-data',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalMasterDataRoomsRoute = PortalMasterDataRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => PortalMasterDataRouteRoute,
} as any)
const PortalMasterDataDepartmentsRoute =
  PortalMasterDataDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => PortalMasterDataRouteRoute,
  } as any)
const PortalMasterDataCollegesRoute =
  PortalMasterDataCollegesRouteImport.update({
    id: '/colleges',
    path: '/colleges',
    getParentRoute: () => PortalMasterDataRouteRoute,
  } as any)
const PortalMasterDataBuildingsRoute =
  PortalMasterDataBuildingsRouteImport.update({
    id: '/buildings',
    path: '/buildings',
    getParentRoute: () => PortalMasterDataRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/portal/master-data': typeof PortalMasterDataRouteRouteWithChildren
  '/portal/home': typeof PortalHomeRoute
  '/portal/master-data/buildings': typeof PortalMasterDataBuildingsRoute
  '/portal/master-data/colleges': typeof PortalMasterDataCollegesRoute
  '/portal/master-data/departments': typeof PortalMasterDataDepartmentsRoute
  '/portal/master-data/rooms': typeof PortalMasterDataRoomsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/portal/master-data': typeof PortalMasterDataRouteRouteWithChildren
  '/portal/home': typeof PortalHomeRoute
  '/portal/master-data/buildings': typeof PortalMasterDataBuildingsRoute
  '/portal/master-data/colleges': typeof PortalMasterDataCollegesRoute
  '/portal/master-data/departments': typeof PortalMasterDataDepartmentsRoute
  '/portal/master-data/rooms': typeof PortalMasterDataRoomsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/portal/master-data': typeof PortalMasterDataRouteRouteWithChildren
  '/portal/home': typeof PortalHomeRoute
  '/portal/master-data/buildings': typeof PortalMasterDataBuildingsRoute
  '/portal/master-data/colleges': typeof PortalMasterDataCollegesRoute
  '/portal/master-data/departments': typeof PortalMasterDataDepartmentsRoute
  '/portal/master-data/rooms': typeof PortalMasterDataRoomsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/portal'
    | '/login'
    | '/portal/master-data'
    | '/portal/home'
    | '/portal/master-data/buildings'
    | '/portal/master-data/colleges'
    | '/portal/master-data/departments'
    | '/portal/master-data/rooms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/portal'
    | '/login'
    | '/portal/master-data'
    | '/portal/home'
    | '/portal/master-data/buildings'
    | '/portal/master-data/colleges'
    | '/portal/master-data/departments'
    | '/portal/master-data/rooms'
  id:
    | '__root__'
    | '/'
    | '/portal'
    | '/login'
    | '/portal/master-data'
    | '/portal/home'
    | '/portal/master-data/buildings'
    | '/portal/master-data/colleges'
    | '/portal/master-data/departments'
    | '/portal/master-data/rooms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/home': {
      id: '/portal/home'
      path: '/home'
      fullPath: '/portal/home'
      preLoaderRoute: typeof PortalHomeRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/master-data': {
      id: '/portal/master-data'
      path: '/master-data'
      fullPath: '/portal/master-data'
      preLoaderRoute: typeof PortalMasterDataRouteRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/master-data/rooms': {
      id: '/portal/master-data/rooms'
      path: '/rooms'
      fullPath: '/portal/master-data/rooms'
      preLoaderRoute: typeof PortalMasterDataRoomsRouteImport
      parentRoute: typeof PortalMasterDataRouteRoute
    }
    '/portal/master-data/departments': {
      id: '/portal/master-data/departments'
      path: '/departments'
      fullPath: '/portal/master-data/departments'
      preLoaderRoute: typeof PortalMasterDataDepartmentsRouteImport
      parentRoute: typeof PortalMasterDataRouteRoute
    }
    '/portal/master-data/colleges': {
      id: '/portal/master-data/colleges'
      path: '/colleges'
      fullPath: '/portal/master-data/colleges'
      preLoaderRoute: typeof PortalMasterDataCollegesRouteImport
      parentRoute: typeof PortalMasterDataRouteRoute
    }
    '/portal/master-data/buildings': {
      id: '/portal/master-data/buildings'
      path: '/buildings'
      fullPath: '/portal/master-data/buildings'
      preLoaderRoute: typeof PortalMasterDataBuildingsRouteImport
      parentRoute: typeof PortalMasterDataRouteRoute
    }
  }
}

interface PortalMasterDataRouteRouteChildren {
  PortalMasterDataBuildingsRoute: typeof PortalMasterDataBuildingsRoute
  PortalMasterDataCollegesRoute: typeof PortalMasterDataCollegesRoute
  PortalMasterDataDepartmentsRoute: typeof PortalMasterDataDepartmentsRoute
  PortalMasterDataRoomsRoute: typeof PortalMasterDataRoomsRoute
}

const PortalMasterDataRouteRouteChildren: PortalMasterDataRouteRouteChildren = {
  PortalMasterDataBuildingsRoute: PortalMasterDataBuildingsRoute,
  PortalMasterDataCollegesRoute: PortalMasterDataCollegesRoute,
  PortalMasterDataDepartmentsRoute: PortalMasterDataDepartmentsRoute,
  PortalMasterDataRoomsRoute: PortalMasterDataRoomsRoute,
}

const PortalMasterDataRouteRouteWithChildren =
  PortalMasterDataRouteRoute._addFileChildren(
    PortalMasterDataRouteRouteChildren,
  )

interface PortalRouteRouteChildren {
  PortalMasterDataRouteRoute: typeof PortalMasterDataRouteRouteWithChildren
  PortalHomeRoute: typeof PortalHomeRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalMasterDataRouteRoute: PortalMasterDataRouteRouteWithChildren,
  PortalHomeRoute: PortalHomeRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
