/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteRouteImport } from './routes/portal/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalHomeRouteImport } from './routes/portal/home'
import { Route as PortalMasterDataManagementRouteRouteImport } from './routes/portal/master-data-management/route'
import { Route as PortalMasterDataManagementRoomsRouteRouteImport } from './routes/portal/master-data-management/rooms/route'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalHomeRoute = PortalHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalMasterDataManagementRouteRoute =
  PortalMasterDataManagementRouteRouteImport.update({
    id: '/master-data-management',
    path: '/master-data-management',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalMasterDataManagementRoomsRouteRoute =
  PortalMasterDataManagementRoomsRouteRouteImport.update({
    id: '/rooms',
    path: '/rooms',
    getParentRoute: () => PortalMasterDataManagementRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/portal/master-data-management': typeof PortalMasterDataManagementRouteRouteWithChildren
  '/portal/home': typeof PortalHomeRoute
  '/portal/master-data-management/rooms': typeof PortalMasterDataManagementRoomsRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/portal/master-data-management': typeof PortalMasterDataManagementRouteRouteWithChildren
  '/portal/home': typeof PortalHomeRoute
  '/portal/master-data-management/rooms': typeof PortalMasterDataManagementRoomsRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/portal/master-data-management': typeof PortalMasterDataManagementRouteRouteWithChildren
  '/portal/home': typeof PortalHomeRoute
  '/portal/master-data-management/rooms': typeof PortalMasterDataManagementRoomsRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/portal'
    | '/login'
    | '/portal/master-data-management'
    | '/portal/home'
    | '/portal/master-data-management/rooms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/portal'
    | '/login'
    | '/portal/master-data-management'
    | '/portal/home'
    | '/portal/master-data-management/rooms'
  id:
    | '__root__'
    | '/'
    | '/portal'
    | '/login'
    | '/portal/master-data-management'
    | '/portal/home'
    | '/portal/master-data-management/rooms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/home': {
      id: '/portal/home'
      path: '/home'
      fullPath: '/portal/home'
      preLoaderRoute: typeof PortalHomeRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/master-data-management': {
      id: '/portal/master-data-management'
      path: '/master-data-management'
      fullPath: '/portal/master-data-management'
      preLoaderRoute: typeof PortalMasterDataManagementRouteRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/master-data-management/rooms': {
      id: '/portal/master-data-management/rooms'
      path: '/rooms'
      fullPath: '/portal/master-data-management/rooms'
      preLoaderRoute: typeof PortalMasterDataManagementRoomsRouteRouteImport
      parentRoute: typeof PortalMasterDataManagementRouteRoute
    }
  }
}

interface PortalMasterDataManagementRouteRouteChildren {
  PortalMasterDataManagementRoomsRouteRoute: typeof PortalMasterDataManagementRoomsRouteRoute
}

const PortalMasterDataManagementRouteRouteChildren: PortalMasterDataManagementRouteRouteChildren =
  {
    PortalMasterDataManagementRoomsRouteRoute:
      PortalMasterDataManagementRoomsRouteRoute,
  }

const PortalMasterDataManagementRouteRouteWithChildren =
  PortalMasterDataManagementRouteRoute._addFileChildren(
    PortalMasterDataManagementRouteRouteChildren,
  )

interface PortalRouteRouteChildren {
  PortalMasterDataManagementRouteRoute: typeof PortalMasterDataManagementRouteRouteWithChildren
  PortalHomeRoute: typeof PortalHomeRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalMasterDataManagementRouteRoute:
    PortalMasterDataManagementRouteRouteWithChildren,
  PortalHomeRoute: PortalHomeRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
