<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.Result" Version="10.1.0"/>
    <PackageReference Include="FluentValidation" Version="12.1.1"/>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1"/>
    <PackageReference Include="MediatR" Version="14.1.0"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Enrollify.Core\Enrollify.Core.csproj"/>
    <ProjectReference Include="..\Enrollify.Analyzers\Enrollify.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
    <ProjectReference Include="..\Enrollify.SharedKernel\Enrollify.SharedKernel.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\ClassSectionScheduling\Specifications\ClassSectionValidationIssues\"/>
  </ItemGroup>

</Project>
